groups:
  - name: konsumer-alerts
    rules:
      - alert: ProcessedMessageDecreasing
        expr: sum(rate(kafka_konsumer_processed_messages_total{job="konsumer"}[1m])) < 0.1
        for: 5m
        labels:
          severity: "critical"
        annotations:
          summary: "Kafka Konsumer processed message decreasing"
          description: "Kafka Konsumer processed message decreasing, current rate: {{ $value }} <http://localhost:3000/d/DlIdtG_4z/kafka-konsumer-dashboard|Grafana>"
